---
- name: Stop Azure Linux VM
  hosts: localhost
  tasks:
    - name: Check if Azure CLI is installed
      command: az --version
      ignore_errors: yes
      register: azure_cli_check

    - name: Install Azure CLI if not found
      become: yes  # Use 'become' for privilege escalation
      command: >-
        if not exist "%ProgramFiles(x86)%\Microsoft SDKs\Azure\CLI2\wbin\az.cmd" (
          curl -o install-az.cmd -sL https://aka.ms/installazurecliwindows
          install-az.cmd
        )
      when: "'az' not in azure_cli_check.stdout"

    - name: Stop the Azure Linux VM
      command: az vm stop --name vm01 --resource-group vmss-rg --no-wait
