---
- name: Stop Azure Linux VM
  hosts: localhost
  tasks:
    - name: Check if Azure CLI is installed
      command: az --version
      ignore_errors: yes
      register: azure_cli_check

    - name: Install Azure CLI if not found
      become: yes  # Use 'become' for privilege escalation
      command: >-
        if [ ! -x "$(command -v az)" ]; then
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
        fi
      when: "'az' not in azure_cli_check.stdout"

    - name: Check if curl is installed
      command: curl --version
      ignore_errors: yes
      register: curl_check

    - name: Install curl if not found
      become: no  # Use 'become' for privilege escalation
      command: >-
        if [ ! -x "$(command -v curl)" ]; then
          # Install curl based on your system's package manager
          # On Debian-based systems (e.g., Ubuntu):
          sudo apt-get update
          sudo apt-get install -y curl
        fi
      when: "'curl' not in curl_check.stdout"

    - name: Stop the Azure Linux VM
      command: az vm stop --name vm01 --resource-group vmss-rg --no-wait
